### ISSUE TITLE
odd error message

### ISSUE THREAD

**Issue by lwb52** [ryanjamurphy/review-obsidian#17] opened 2021-01-27 19:58 UTC
Obs.v.0.10.7—10.10 (OSX10.14.6): in one Vault (used for testing only, and applying no Theme), upon opening the Vault, the Review plugin throws a brief error message that reports it cannot locate the Natural Language Dates (NLD) plugin to work; however, both have been installed, removed, re·installed, turned on&off, and the vault reloaded or Obs restarted, all multiple times in various orders—but to no effect

the same error message ends by referring to installing and turning on NLD before using the (presumably) unrelated Vantage search plugin, so it's unclear why and when to install Vantage…

this error does not occur in the other vaults where both NLD & Review are installed

**Comment by lwb52** [comment] 2021-01-28 10:09
created brand new vault with only NLD, Review, and Vantage: no issue at all! is this possibly just a one-off???

**Comment by ryanjamurphy** [comment] 2021-01-28 19:08
Hah, we'll cross our fingers. Probably just weather in Obsidian? Thanks for the follow up!

**Comment by montemartin** [comment] 2021-02-04 04:00
I initially came here to report the same issue, but taking a look at the dev console it seems NLD is missing a CSS file. 
`Failed to load resource: the server responded with a status of 404 ()…https://github.com/argenos/nldates-obsidian/releases/download/0.3.3/styles.css:1`

I'm guessing that is what causes the error message. It doesn't seem to have an effect on either plugin. I'm not sure what NLD would need its own style sheet for, and looking at the repo it's only contents are `body {color: red;}`. I'm not sure how styles are scoped for plugins, but I definitely don't want that loading globally! I'll file an issue on the NLD repo.

**Comment by montemartin** [comment] 2021-02-04 05:55
After a little more digging I found that definitely isn't the cause of the error. (It happens when I try to update NLD, which is a different issue). The error I'm getting is from [Line 16 of Review](https://github.com/ryanjamurphy/review-obsidian/blob/b7e927f7a362b4910fb9ccc7394831fc8f5625e1/main.ts#L16).

I did a little testing and it looks like this check for NLD should work correctly, so still not sure what the issue is. Sorry I can't offer more help.

**Comment by ryanjamurphy** [comment] 2021-02-04 22:17
Thanks for the follow-up. I don't _think_ it's the CSS file, as most plugins are missing one. I imagine there's a better way to ensure NLD is installed, so maybe someday I'll write one and this issue will go away. 'Til then I'll keep collecting reports!

**Comment by lwb52** [comment] 2021-02-05 01:03
I just find it very odd – possibly even revealing – that it only happens on my setup with just one vault of the two I use for testing plugins rather than data—I rarely modify their themes because some themes don’t do well with some plugins, and both can have issues with Obs. app upgrades.

In fact, something specific for me to investigate: now that I think of it, the affected vault is the only one that has the standard light theme; the unaffected vault has the standard dark theme; all other vaults use “community” themes…

-L.W. Brown
via 8s+

**Comment by liamcain** [comment] 2021-02-05 01:55
This should be fixed by #18. Because the plugin load order isn't guaranteed, I changed when the check is done. (So it will properly wait until all plugins are loaded before checking.)

**Comment by lwb52** [comment] 2021-02-05 05:30
Thanks—changing the themes had absolutely no effect…

**Closed as completed** 2021-02-06 17:32 UTC

**Comment by danieltomasz** [comment] 2021-02-09 14:32
I was getting the same error message, uninstalling and installing the plugin again make the error message disappear.

**Comment by lwb52** [comment] 2021-02-10 08:07
I tried that, but it didn’t seem to work.
My remedy, finally, was just simply to replace the plugin with a copy from a vault where it worked correctly…
